package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/trungdlp/ai-gateway-testkit/cases"
	"github.com/trungdlp/ai-gateway-testkit/internal/profile"
	"github.com/trungdlp/ai-gateway-testkit/internal/testcase"
)

const (
	catalogDirectory = "catalog/cases"
	docsDirectory    = "docs/cases"
)

func main() {
	check := flag.Bool("check", false, "fail when generated case files are stale")
	flag.Parse()

	catalog, err := cases.Catalog()
	if err != nil {
		fail(err)
	}
	if _, err := profile.Load(catalog); err != nil {
		fail(err)
	}

	catalogFiles := make(map[string][]byte)
	docFiles := make(map[string][]byte)
	for _, definition := range catalog.Definitions() {
		sourcePath, err := caseSourcePath(definition.ID)
		if err != nil {
			fail(err)
		}
		data, err := json.MarshalIndent(definition, "", "  ")
		if err != nil {
			fail(err)
		}
		catalogFiles[definition.ID+".json"] = append(data, '\n')
		docFiles[definition.ID+".md"] = []byte(renderCaseMarkdown(definition, sourcePath))
	}

	if err := syncDirectory(catalogDirectory, ".json", catalogFiles, *check); err != nil {
		fail(err)
	}
	if err := syncDirectory(docsDirectory, ".md", docFiles, *check); err != nil {
		fail(err)
	}
}

func syncDirectory(directory, generatedExtension string, expected map[string][]byte, check bool) error {
	if check {
		for name, content := range expected {
			path := filepath.Join(directory, name)
			existing, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(existing, content) {
				return fmt.Errorf("generated file %s is stale; run go generate ./...", path)
			}
		}
	}

	entries, err := os.ReadDir(directory)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != generatedExtension {
			continue
		}
		if _, ok := expected[entry.Name()]; ok {
			continue
		}
		path := filepath.Join(directory, entry.Name())
		if check {
			return fmt.Errorf("orphan generated file %s; run go generate ./...", path)
		}
		if err := os.Remove(path); err != nil {
			return err
		}
	}
	if check {
		return nil
	}

	if err := os.MkdirAll(directory, 0o755); err != nil {
		return err
	}
	names := make([]string, 0, len(expected))
	for name := range expected {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if err := os.WriteFile(filepath.Join(directory, name), expected[name], 0o644); err != nil {
			return err
		}
	}
	return nil
}

func renderCaseMarkdown(definition testcase.Definition, sourcePath string) string {
	var output strings.Builder
	fmt.Fprintf(&output, "# %s: %s\n\n", definition.ID, definition.Title)
	output.WriteString("<!-- This file is generated by cmd/cataloggen. Do not edit it directly. -->\n\n")
	fmt.Fprintf(&output, "%s\n\n", definition.Description)
	fmt.Fprintf(&output, "Source: [`%s`](../../%s)\n\n", filepath.Base(sourcePath), filepath.ToSlash(sourcePath))
	output.WriteString("## Classification\n\n")
	output.WriteString("| Field | Value |\n| --- | --- |\n")
	fmt.Fprintf(&output, "| Revision | %d |\n", definition.Revision)
	fmt.Fprintf(&output, "| Layer | `%s` |\n", definition.Layer)
	fmt.Fprintf(&output, "| Suite | `%s` |\n", definition.Suite)
	fmt.Fprintf(&output, "| Area | `%s` |\n", definition.Area)
	fmt.Fprintf(&output, "| Stability | `%s` |\n", definition.Stability)
	fmt.Fprintf(&output, "| Determinism | `%s` |\n", definition.Determinism)

	output.WriteString("\n## Execution contract\n\n")
	fmt.Fprintf(&output, "- Requests: %d\n", definition.Cost.Requests)
	fmt.Fprintf(&output, "- Maximum input tokens: %d\n", definition.Cost.MaxInputTokens)
	fmt.Fprintf(&output, "- Maximum output tokens: %d\n", definition.Cost.MaxOutputTokens)
	fmt.Fprintf(&output, "- Mutation: `%s`\n", definition.Risk.Mutation)
	fmt.Fprintf(&output, "- Cleanup required: %t\n", definition.Risk.CleanupRequired)
	fmt.Fprintf(&output, "- Contains model output: %t\n", definition.Risk.ContainsOutput)
	writeList(&output, "Dependencies", definition.DependsOn)
	writeList(&output, "Preconditions", definition.Preconditions)

	output.WriteString("\n## Assertions\n\n")
	output.WriteString("| ID | Requirement | Impact | Contract |\n| --- | --- | --- | --- |\n")
	for _, assertion := range definition.Assertions {
		fmt.Fprintf(&output, "| `%s/%s` | `%s` | `%s` | %s |\n", definition.ID, assertion.ID, assertion.Requirement, assertion.Impact, escapeTable(assertion.Title))
	}

	if len(definition.SpecReferences) > 0 {
		output.WriteString("\n## Specification references\n\n")
		for _, reference := range definition.SpecReferences {
			label := reference.Title
			if reference.Section != "" {
				label += " — " + reference.Section
			}
			fmt.Fprintf(&output, "- [%s](%s)\n", label, reference.URL)
		}
	}
	return output.String()
}

func writeList(output *strings.Builder, label string, values []string) {
	fmt.Fprintf(output, "- %s: ", label)
	if len(values) == 0 {
		output.WriteString("none\n")
		return
	}
	formatted := make([]string, len(values))
	for i, value := range values {
		formatted[i] = "`" + value + "`"
	}
	output.WriteString(strings.Join(formatted, ", ") + "\n")
}

func caseFilename(id string) string {
	return strings.ToLower(strings.ReplaceAll(id, "-", "_"))
}

func caseSourcePath(id string) (string, error) {
	pattern := filepath.Join("cases", "*", caseFilename(id)+".go")
	matches, err := filepath.Glob(pattern)
	if err != nil {
		return "", err
	}
	if len(matches) != 1 {
		return "", fmt.Errorf("case %s must have exactly one source file matching %s; found %d", id, pattern, len(matches))
	}
	return matches[0], nil
}

func escapeTable(value string) string {
	return strings.ReplaceAll(value, "|", "\\|")
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
